### ISSUE TITLE
tag new release

### ISSUE THREAD

**Issue by lazarusA** [JuliaGeo/TileProviders.jl#19]
The current release is currently outdated, hence having a new one would be nice. Plus, CartoDB would work with Tyler.

**Comment by visr** [comment]
Yeah there are quite some unreleased commits: https://github.com/JuliaGeo/TileProviders.jl/compare/v0.1.2...main

Project.toml version is v0.1.4, but should probably be set back to v0.1.3, since that release, triggered in https://github.com/JuliaGeo/TileProviders.jl/commit/b66e195055ef323f52392ca23148ec1bc32cd2ab, somehow was never merged in General.

Also needs to add

```toml
[compat]
Dates = "1"
```
